In [1]:
import numpy as np

In [9]:
valoraciones = np.array([[8,7,6,5], [5,6,4,7], [7,5,5,6]])
valoraciones

array([[8, 7, 6, 5],
       [5, 6, 4, 7],
       [7, 5, 5, 6]])

In [3]:
#Dimensiones Filas y Luego Columnas
#por eso fila 0, y columna 1, sería el 7.
valoraciones[0][1] 

7

In [4]:
valoraciones[0,1]

7

In [10]:
valoraciones2 = np.array([[[8,7,6,5], [5,6,4,7]], [[7,5,5,6], [8,7,6,5]], [[5,6,4,7], [7,5,5,6]]])
valoraciones2

array([[[8, 7, 6, 5],
        [5, 6, 4, 7]],

       [[7, 5, 5, 6],
        [8, 7, 6, 5]],

       [[5, 6, 4, 7],
        [7, 5, 5, 6]]])

In [11]:
valoraciones2[0,1,2]

4

In [12]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
valoraciones2 + np.ones((3,2,4))

array([[[9., 8., 7., 6.],
        [6., 7., 5., 8.]],

       [[8., 6., 6., 7.],
        [9., 8., 7., 6.]],

       [[6., 7., 5., 8.],
        [8., 6., 6., 7.]]])

In [14]:
np.mean(valoraciones2)

5.916666666666667

In [17]:
np.mean(valoraciones2, axis = 2)

array([[6.5 , 5.5 ],
       [5.75, 6.5 ],
       [5.5 , 5.75]])

In [18]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
np.median(df["Columna1"])

In [20]:
(np.random.rand(2,2)) * 10

array([[6.71634879, 5.53984131],
       [4.86150096, 2.08173303]])